name: Theme Assigner
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keywordsToAssigneesMap = {
              BurntSienna: ["pjaspinski"],
              Default: ["Blacksuan19"],
              Dreary: ["CharlieS1103"],
              Dribbblish: ["khanhas"],
              Glaze: ["CharlieS1103"],
              Onepunch: ["okarin001"],
              Sleek: ["harbassan"],
              Turntable: ["grasonchan"],
              Ziro: ["schnensch0"],
              Flow: ["ian-Liaozy", "Ruixi-Zhang"],
              Matte: ["darkthemer"],
              Blossom: ["Robatortas"],
              Nightlight: ["iTenerai"],
            };

            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const title = issue.data.title;
            const body = issue.data.body;

            const assignees = [];

            for (const [keyword, assignee] of Object.entries(keywordsToAssigneesMap)) {
              if (title.includes(keyword) || body.includes(keyword)) {
                if (Array.isArray(assignee)) {
                  assignees.push(...assignee);
                } else {
                  assignees.push(assignee);
                }
              }
            }

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: assignees,
            });
